title: "Julien Romero"
description: "Associate Professor in Computer Science â€“ AI & Machine Learning"
baseurl: ""
url: "https://aunsiels.github.io/personal-website"
permalink: /:categories/:year/:month/:day/:title/


markdown: kramdown

# Keep things simple
theme: null

# Build settings
exclude:
  - README.md

